[package]
name = "smtc_windows"
version = "0.1.4"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
windows-future = "0.3.*"
windows-core = "0.62.*"
anyhow = '1'

[dependencies.windows]
version = '0.62.*'
features = ['Media', 'Media_Playback', 'Foundation', 'Storage_Streams']
